version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  timescaledb:
    image: timescale/timescaledb:latest-pg10
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "clash"
